#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2014 OpenWrt.org
# Put this inside /etc/init.d/

START=91
STOP=10
USE_PROCD=1

PYTHON='/usr/bin/python3'
DWC_PY='/root/dwc2-for-klipper-socket/web_dwc2.py'

start_service() {
    procd_open_instance
    procd_set_param command "$PYTHON" \
        "$DWC_PY"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
