#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2014 OpenWrt.org
# Put this inside /etc/init.d/

START=99
STOP=10
USE_PROCD=1
# Load configuration from UCI
config_load klipper
# Load values from UCI into variables used below
config_get PYTHON path python
config_get KLIPPY_PY path klipper_py
config_get KLIPPER_LOG path klipper_log
config_get PRINTER_CFG path printer_cfg

start_service() {
    procd_open_instance
    procd_set_param command "$PYTHON" \
        "$KLIPPY_PY" \
        "$PRINTER_CFG" -l "$KLIPPER_LOG" -a /tmp/klippy_uds
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
