#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2014 OpenWrt.org
# Put this inside /etc/init.d/

START=99
STOP=10
USE_PROCD=1

PYTHON='/usr/bin/python3'
KLIPPY_PY='/root/klipper/klippy/klippy.py'
PRINTER_CFG='/root/printer_data/config/printer.cfg'
KLIPPER_LOG='/root/printer_data/logs/klippy.log'

start_service() {
    procd_open_instance
    procd_set_param command "$PYTHON" \
        "$KLIPPY_PY" \
        "$PRINTER_CFG" -l "$KLIPPER_LOG" -a /tmp/klippy_uds
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
